### ISSUE TITLE
Sensor Type "step_detector" absent in code, but mentioned

### ISSUE THREAD

**Issue by aeifr** [umer0586/SensorServer#59]
Hi,

I noticed during trying out the app/websocket, I noticed, the step_detector is absent. It's mentioned in the readme-ov-file#usage section.
I choose it due to it's mentioned step detector "capability".

My question:
Is there any chance the step detection gets added? At the moment it's t he single reason why I choose this fairly quick without thinking.

**Comment by umer0586** [comment]
In the README#usage section, I listed "step_detector" as an example because the device I used for testing happened to have that sensor.  Unfortunately, different devices have different sensors available.  It's possible your device simply doesn't have a dedicated step detector. But there are other ways to detect steps using `accelerometer` which is available in almost every device see https://medium.com/@huuphuoc1396/android-step-detector-using-sensors-9f1a265a6069
